---
# Issue removal tasks

- name: Check issue
  ansible.builtin.assert:
    that: redmine_issue_search_result | length in [0,1]
    quiet: true
    fail_msg: Found more than one issue to remove

- name: Remove issue in redmine
  ansible.builtin.uri:
    url: "{{ lookup('template', 'url.j2') | trim }}"
    method: DELETE
    validate_certs: "{{ redmine_issue_validate_certs | bool }}"
    headers:
      X-Redmine-API-Key: "{{ redmine_issue_api_password }}"
    body_format: json
    return_content: true
    timeout: "{{ redmine_issue_timeout }}"
  when: redmine_issue_search_result | length == 1
  register: redmine_issue_remove_issue_result
  changed_when: redmine_issue_remove_issue_result.status == 201
  failed_when: redmine_issue_remove_issue_result.status != 201
  no_log: "{{ redmine_issue_no_log | bool | default(false) }}"
