---

- name: Setup redmine issue
  block:
    - include_tasks: search.yml

    - include_tasks: present.yml
      when: redmine_issue_state | default("present") == "present"

    - include_tasks: absent.yml
      when: redmine_issue_state | default("present") == "absent"

    - include_tasks: fact.yml
  tags:
    - role::redmine_issue
