---
- name: Verify
  hosts: molecule_hosts
  gather_facts: false
  tasks:
    - name: Search redmine issue
      ansible.builtin.uri:
        url: >-
          {{ redmine_issue_server_url
             + "/projects/"
             + redmine_issue_project_name
             + "/issues.json" }}
        method: GET
        validate_certs: "{{ redmine_issue_validate_certs }}"
        headers:
          X-Redmine-API-Key: "{{ redmine_issue_api_password }}"
        body_format: json
        body: "{{ redmine_issue_fields }}"
        return_content: true
        timeout: 60
      register: search_issue_result

    - name: Ensure redmine issue is created just once
      ansible.builtin.assert:
        that:
          - search_issue_result.json.total_count == 1
